### ISSUE TITLE
in windiows 10, run mstsc error

### ISSUE THREAD

**Issue by fenmei** [MicrosoftDocs/windowsserverdocs.zh-tw#2]
[請在此輸入您的意見]
In windows 10 OS, execute  mstsc /v:hostname:port, it does not work.
The error message shows like this "..the computer name is not accepted: blank or :/.."

The same command is well done in Windows 7.

Please help.
Thank a lots.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 8042b913-6ff5-2876-f60f-5387e34d8bcb
* Version Independent ID: 6cea6efc-cc44-b77a-8d99-3de546b4f519
* Content: [變更遠端桌面中的接聽連接埠](https://docs.microsoft.com/zh-tw/windows-server/remote/remote-desktop-services/clients/change-listening-port#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/change-listening-port.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-tw/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/change-listening-port.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by srvbpigh** [comment]
Hello, @fenmei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @fenmei 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
